
find_package(protobuf CONFIG REQUIRED)
function(add_neko_proto binary)
	file(GLOB_RECURSE proto_files "${CMAKE_CURRENT_SOURCE_DIR}/proto/*.proto")
	set(proto_bin_name "${binary}_Proto")
    MESSAGE("Adding ${proto_bin_name}")
	add_library(${proto_bin_name} STATIC ${proto_files})
    protobuf_generate(TARGET ${proto_bin_name} LANGUAGE cpp)
    protobuf_generate(TARGET ${proto_bin_name} LANGUAGE python)
    target_include_directories(${proto_bin_name} PUBLIC ${CMAKE_CURRENT_BINARY_DIR})
	target_link_libraries(${proto_bin_name} PUBLIC protobuf::libprotobuf-lite protobuf::libprotoc protobuf::libprotobuf)
    target_link_libraries(${binary} PUBLIC ${proto_bin_name})
	set_target_properties (${proto_bin_name} PROPERTIES FOLDER Neko/Proto)
endfunction()