function(add_neko_test binary)
	enable_testing()
	file(GLOB_RECURSE test_files "${CMAKE_CURRENT_SOURCE_DIR}/test/*.cpp")
	set(test_bin_name "${binary}_Test")
	add_executable(${test_bin_name} ${test_files})
	target_link_libraries(${test_bin_name} ${binary} gtest gtest_main)
	target_include_directories(${test_bin_name} PUBLIC ${GOOGLE_TEST_DIR}/include)
	add_test(NAME ${test_bin_name} COMMAND ${test_bin_name})
	NEKO_BIN_CONFIG(${test_bin_name})
	set_target_properties (${test_bin_name} PROPERTIES FOLDER Neko/Test)
endfunction()